// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:ai_voice2task_app/features/tasks/domain/entities/task.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(TaskAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(TaskAdapter());
  }
}
